import sys
import os
import csv
from shutil import copy

"""
    Run after sepUsers.py and mergeSensors.py.

    This script organizes the data for leave-one-out cross validation. In particular it creates
    a folder for each user with inside a "train" folder and an "eval" folder. The train folder
    contains all the data generated by the other users, while the eval folder contains the 
    data generated by the user.
"""

dataDir = "/Path/To/Data/Dir"

users = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
activities = ["bike", "sit", "stand", "walk", "stairsup", "stairsdown"]

for user in users:
    user_dir_path = os.path.join(dataDir, "user_" + user)
    os.mkdir(user_dir_path)
    os.mkdir(os.path.join(user_dir_path, "train"))
    os.mkdir(os.path.join(user_dir_path, "eval"))
    
for user in users:
    for activity in activities:
        dir = os.path.join(dataDir, user, "final", activity)
        filelist = os.listdir(dir)
        for file in filelist:
            filepath = os.path.join(dataDir, user, "final", activity, file)
            for u in users:
                if u != user:
                    outdir = os.path.join(dataDir, "a_user_" + u, "train")
                    copy(filepath, outdir)
                else:
                    outdir = os.path.join(dataDir, "a_user_" + u, "eval")
                    copy(filepath, outdir)